import nltk
from nltk import PCFG
from nltk.parse import ViterbiParser

grammar = PCFG.fromstring("""
S -> NP VP [1.0]
NP -> Det N [0.6] | 'John' [0.4]
VP -> V NP [0.7] | V [0.3]
Det -> 'the' [1.0]
N -> 'dog' [0.5] | 'cat' [0.5]
V -> 'sees' [1.0]
""")

sentence = "John sees the dog".split()
parser = ViterbiParser(grammar)

try:
    for tree in parser.parse(sentence):
        print(tree)
        print("Probability:", tree.prob())
except ValueError:
    print("Sentence is not generated by the grammar.")
